In [112]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [127]:
smartphones = pd.read_csv('smartphones.csv')

In [128]:
smartphones.dropna(inplace=True)
smartphones.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 727 entries, 0 to 728
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Brand             727 non-null    object
 1   Model             727 non-null    object
 2   Storage           727 non-null    object
 3   Colour            727 non-null    object
 4   Operating System  727 non-null    object
dtypes: object(5)
memory usage: 34.1+ KB


In [129]:
smartphones.head(50)

Brand                  Model Storage      Colour Operating System
0   Blackberry                   PRIV    32GB     schwarz          Android
1   Blackberry                   KEY2    64GB     schwarz          Android
2   Blackberry                   KEY2    64GB      silber          Android
3   Blackberry                 Motion    32GB       black          Android
4   Blackberry                 KEYone    64GB     schwarz          Android
5   Blackberry          KEY2 Dual SIM    64GB     schwarz          Android
6   Blackberry         KEY2 Dual SIM    128GB     schwarz          Android
7   Blackberry       KEY2 LE Dual SIM    64GB        blau          Android
8   Blackberry       KEY2 LE Dual SIM    64GB         red          Android
9   Blackberry       KEY2 LE Dual SIM    64GB  champagner          Android
10  Blackberry                 DTEK50    16GB     schwarz          Android
11  Blackberry                 KEYone    32GB      silber          Android
12  Blackberry        Motion Dual SIM    32GB       black          Android
13  Blackberry                 KEYone    64GB      bronze          Android
14  Blackberry                   PRIV    32GB     schwarz          Android
15     Samsung  Note 10 Plus Dual SIM   256GB       black          Android
16     Samsung  Note 10 Plus Dual SIM   256GB        glow          Android
17     Samsung      S10 Plus Dual SIM   128GB       black          Android
18     Samsung                S8 Plus    64GB        grey          Android
19     Samsung      S10 Plus Dual SIM   512GB       white          Android
20     Samsung                S9 DuoS    64GB        blue          Android
21     Samsung      S10 Plus Dual SIM   512GB       black          Android
22     Samsung              A5 (2017)    32GB         sky          Android
23     Samsung                     S9    64GB       black          Android
24     Samsung       Note 10 Dual SIM   256GB       black          Android
25     Samsung                     S8    64GB       black          Android
26     Samsung          S10e Dual SIM   128GB       black          Android
27     Samsung                     S7    32GB      silver          Android
28     Samsung                     S7    32GB        gold          Android
29     Samsung                 Note 4    32GB       black          Android
30     Samsung                S7 edge    32GB    platinum          Android
31     Samsung           S9 Plus DuoS    64GB      purple          Android
32     Samsung      S10 Plus Dual SIM   128GB       white          Android
33     Samsung           S9 Plus DuoS    64GB        blue          Android
34     Samsung                S6 Edge    32GB    sapphire          Android
35     Samsung                 S5 Neo    16GB       black          Android
36     Samsung            Note 9 DUOS   128GB       black          Android
37     Samsung                     S6    32GB       topaz          Android
38     Samsung           A70 Dual SIM   128GB       white          Android
39     Samsung                 Note 8    64GB       black          Android
40     Samsung              A5 (2017)    32GB        sand          Android
41     Samsung  S20 Ultra 5G Dual SIM   128GB        gray          Android
42     Samsung                S7 edge    32GB        onyx          Android
43     Samsung                S8 Plus    64GB      silver          Android
44     Samsung     A6 (2018) Dual SIM    32GB       black          Android
45     Samsung       Note 10 Dual SIM   256GB        glow          Android
46     Samsung     A7 (2018) Dual SIM    64GB       black          Android
47     Samsung                S6 Edge    32GB    platinum          Android
48     Samsung              A3 (2017)    16GB        sand          Android
49     Samsung                     S6    64GB    sapphire          Android

In [130]:
smartphones['Colour'].unique()

array(['schwarz', 'silber', 'black', 'blau', 'red', 'champagner',
       'bronze', 'glow', 'grey', 'white', 'blue', 'sky', 'silver', 'gold',
       'platinum', 'purple', 'sapphire', 'topaz', 'sand', 'gray', 'onyx',
       'pearl', 'lavender', 'green', 'pink', 'titanium', 'mist', 'yellow',
       'cloud', 'coral', 'emerald', 'rosegold', 'frost', 'sea green',
       'violett', 'chrom', 'grau', 'koralle', 'mandarinrot', 'rot',
       'kupfer', 'rose gold', 'orange', 'anthrazit', 'weiss',
       'space grau', 'night green', 'diamantschwarz', 'spacegrau', 'gelb',
       'white silver', 'schwarz graphit', 'graphit', 'pazifikblau',
       'hellgrau'], dtype=object)

In [131]:
colour = {'schwarz': 'black', 'silber': 'silver', 'blau': 'blue', 'champagner':'champagne','violett': 'violet', 'grau': 'gray',
         'koralle':'coral',  'mandarinrot':'mandarin red', 'rot':'red', 'kupfer': 'copper', 'anthrazit':'anthracite',
         'weiss': 'white','space grau': 'space gray', 'spacegrau': 'space gray', 'gelb': 'yellow', 'schwarz graphit': 'black graphite',
         'graphit': 'graphite', 'pazifikblau': 'pacific blue', 'hellgrau': 'light gray'}

In [132]:
smartphones.replace({'Colour': colour}, inplace=True)

In [133]:
smartphones.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 727 entries, 0 to 728
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Brand             727 non-null    object
 1   Model             727 non-null    object
 2   Storage           727 non-null    object
 3   Colour            727 non-null    object
 4   Operating System  727 non-null    object
dtypes: object(5)
memory usage: 34.1+ KB


In [134]:
smartphones.head()

Brand   Model Storage  Colour Operating System
0  Blackberry    PRIV    32GB   black          Android
1  Blackberry    KEY2    64GB   black          Android
2  Blackberry    KEY2    64GB  silver          Android
3  Blackberry  Motion    32GB   black          Android
4  Blackberry  KEYone    64GB   black          Android

In [135]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

In [148]:
X = smartphones.drop(['Brand','Operating System'], axis =1)
y = smartphones['Operating System']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=11)

In [149]:
#SVC MODEL
from sklearn.svm import SVC
svc_model = make_pipeline(OneHotEncoder(handle_unknown='ignore'), SVC())
svc_model.fit(X_train, y_train)
svc_model_pred = svc_model.predict(X_test)

In [150]:
print(confusion_matrix(y_test, svc_model_pred))
print('\n')
print(classification_report(y_test, svc_model_pred))

[[102   0   0   9]
 [  2   3   0   2]
 [  5   0   9   0]
 [  2   0   0  85]]


              precision    recall  f1-score   support

     Android       0.92      0.92      0.92       111
        BBOS       1.00      0.43      0.60         7
     Windows       1.00      0.64      0.78        14
         iOS       0.89      0.98      0.93        87

    accuracy                           0.91       219
   macro avg       0.95      0.74      0.81       219
weighted avg       0.91      0.91      0.90       219



In [151]:
#Random Forest Classification
from sklearn.ensemble import RandomForestClassifier

rfc_model = make_pipeline(OneHotEncoder(handle_unknown='ignore'), RandomForestClassifier())
rfc_model.fit(X_train, y_train)
rfc_model_pred = rfc_model.predict(X_test)

In [152]:
print(confusion_matrix(y_test, rfc_model_pred))
print('\n')
print(classification_report(y_test, rfc_model_pred))

[[104   0   0   7]
 [  3   2   0   2]
 [  2   0  12   0]
 [  4   0   0  83]]


              precision    recall  f1-score   support

     Android       0.92      0.94      0.93       111
        BBOS       1.00      0.29      0.44         7
     Windows       1.00      0.86      0.92        14
         iOS       0.90      0.95      0.93        87

    accuracy                           0.92       219
   macro avg       0.96      0.76      0.81       219
weighted avg       0.92      0.92      0.91       219



In [163]:
svc_model.predict([['Lumia 635', '8GB', 'black']])

array(['Windows'], dtype=object)